# lambda functions
* anonymous functions inline singel-use

In [2]:
y = lambda x:x**2

In [3]:
y(5)

25

In [4]:
y = lambda x1, x2:(x1**2 + x2**2)

In [5]:
y(3, 4)

25

In [7]:
nums =[10, 12, 15, 20]

In [8]:
list(map(lambda x: x**2, nums))

[100, 144, 225, 400]

In [ ]:
%timeit # magic function is use to "time" a block of code

In [10]:
nums =[[1,2,3], [4,5,6],[7,8,9]]

In [11]:
import numpy as np

matrix = np.array(nums)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
matrix.shape

(3, 3)

In [13]:
type(matrix)

numpy.ndarray

In [14]:
matrix.diagonal()

array([1, 5, 9])

In [16]:
v = [1,2,3,4,5]
arr = np.array(v)
arr

array([1, 2, 3, 4, 5])

In [17]:
arr.shape

(5,)

In [18]:
arr*100 #boradcasting

array([100, 200, 300, 400, 500])

In [19]:
arr+100

array([101, 102, 103, 104, 105])

In [21]:
mat = np.array(nums)
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
mat.shape

(3, 3)

In [27]:
arr = np.arange(10, 21, 2) # get numbers between 10 and 21 wiht increment of  2
arr

array([10, 12, 14, 16, 18, 20])

In [28]:
arr = np.arange(0, 2e6, 2.5)
arr

array([0.0000000e+00, 2.5000000e+00, 5.0000000e+00, ..., 1.9999925e+06,
       1.9999950e+06, 1.9999975e+06])

In [29]:
arr.shape

(800000,)

In [30]:
np.zeros(3)

array([0., 0., 0.])

In [31]:
np.zeros((3,4)) #for memory pre location

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [33]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [34]:
np.eye(4) # identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [35]:
v =[1,2,3,4,5]
np.diag(v) # diagonal matrix

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

# Random nos

In [36]:
np.random.rand()

0.11269618606023923

In [37]:
arr =np.random.rand(3,4)
arr

array([[0.42530762, 0.36831765, 0.37418581, 0.16902793],
       [0.7279624 , 0.01022962, 0.5374308 , 0.72289253],
       [0.95867603, 0.16462223, 0.59548524, 0.97640843]])

In [42]:
arr = arr.round(2)
arr

array([[0.43, 0.37, 0.37, 0.17],
       [0.73, 0.01, 0.54, 0.72],
       [0.96, 0.16, 0.6 , 0.98]])

In [41]:
np.round(np.random.rand(3,4),3)

array([[0.316, 0.473, 0.071, 0.86 ],
       [0.854, 0.922, 0.298, 0.185],
       [0.992, 0.24 , 0.384, 0.255]])

In [48]:
arr =np.random.randn(1000, 1000) #here the random nos generatedare in standard normal distribution

In [49]:
arr.mean()

-0.0005671134032933803

In [50]:
arr.std()

0.9999114050686542

In [51]:
arr.min()

-4.538956153750673

In [52]:
arr.max()

5.116340591374213

In [53]:
arr.dtype

dtype('float64')

In [54]:
print(np.finfo(float).eps) #precision fro float64
print(np.finfo(np.float32).eps)

2.220446049250313e-16
1.1920929e-07


In [55]:
a=1.1234567890123456
b=1.1234567890123457
a==b

True

In [57]:
a=1.123456789012348
b=1.123456789012345
a==b

False

In [58]:
0.3-0.2-0.1

-2.7755575615628914e-17

In [60]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [63]:
np.linalg.det(matrix)

-9.51619735392994e-16

In [64]:
np.linalg.inv(matrix)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [65]:
arr=np.random.rand(3,3)
arr

array([[0.66232132, 0.58559958, 0.43893038],
       [0.36257029, 0.43836439, 0.68327055],
       [0.18158678, 0.41021155, 0.72791796]])

In [67]:
np.linalg.inv(arr)

array([[ -1.50132821,   9.5250906 ,  -8.03556944],
       [  5.41020872, -15.56777851,  11.35059173],
       [ -2.67435186,   6.39694617,  -3.0181844 ]])

In [68]:
np.pi

3.141592653589793

In [71]:
np.cos(0)

1.0

In [69]:
np.cos(np.pi)

-1.0

In [72]:
np.cos(np.pi/2)

6.123233995736766e-17

# Indexing & slicing